### ISSUE TITLE
Naming coherence (py_cube, py-cube, pycube)

### ISSUE THREAD

**Issue by ptbrowne** [Kronmar-Bafu/pylindas#4]
Right now, there are several variations of pycube used.

- py_cube as directory name in the repository
- pycube as the name of the repository
- py-cube as title in the README, and as repository name in pip install command (yet to come)

I think it would be easier to use "pycube" everywhere.

**Comment by Kronmar-Bafu** [comment]
Good catch. I'll take a look later today.

**Comment by Kronmar-Bafu** [comment]
However, pycube is already taken in [pip](https://pypi.org/project/pycube/)

So, most likely I'll go with py-cube.

**Comment by ptbrowne** [comment]
Ah OK, that's unfortunate. The CLI command will remain pycube though for simplicity ?

**Comment by Kronmar-Bafu** [comment]
I would say so, yes

**Comment by Kronmar-Bafu** [comment]
After a small rebranding (i.e. the package is now called `pylindas` with a sub-package `pycube`), we should be able to close this now.
